config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: 'public' do
    root to: "homes#top"
    get 'homes/about'
    get "customers/current_customer" => "customers#show"
    get "customers/confirm"
    patch "customers/withdraw" => "customers#withdraw"
    delete "cart_items/destroy_all"
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks"
    resources :items, only: [:index, :show]
    resources :customers, only: [:edit, :update, :withdraw]
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :create, :index, :show]
  end

  namespace :admin do
    root to: "homes#top"
    get "orders/customer_show/:id" => "orders#customer_show"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  has_many :order_details
  belongs_to :customer

  validates :postal_code, presence: true, length: {is: 7}, numericality: true
  validates :address, presence: true
  validates :name, presence: true, length: {minimum: 2}
  validates :payment_method, presence: true

  enum status: {
    wait_payment: 0,
    confirm_payment: 1,
    making: 2,
    preparing_ship: 3,
    finish_prepare: 4
  }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details
    if @order.status == "confirm_payment"
      @order_details.each do |order_detail|
        order_detail.update(making_status: 1)
      end
    end
    redirect_to admin_order_path(@order.id)
  end

  def customer_show
    @customer = Customer.find(params[:id])
    @orders = @customer.orders.page(params[:page]).per(10)
  end

  private
    def order_params
      params.require(:order).permit(:status)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/customer_show.html.erb
<div class="container">
  <div class="row">
    <h4 class="mt-5 mx-5 px-4 bg-light">
      <%= @customer.last_name %><%= @customer.first_name %>さんの注文履歴
    </h4>
  </div>

  <table class="table col-9 mx-auto my-4">
    <thead class="thead-light text-center">
      <tr>
        <th>購入日時</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <tbody class="text-center">
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to admin_order_path(order.id), class: "link" do %>
              <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
            <% end %>
          </td>
          <td>
            <% @sum = 0 %>
            <% order.order_details.each do |order_detail| %>
              <% @sum += order_detail.amount %>
            <% end %>
            <%= @sum %>
          </td>
          <td><%= order.status_i18n %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="row justify-content-center mb-4">
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="mt-5 mx-5 px-4 bg-light">注文履歴詳細</h4>
  </div>

  <table class="my-4">
    <tr>
      <th class="text-nowrap"><h5><strong>購入者</strong></h5></th>
      <td class="text-nowrap">
        <%= link_to admin_path(@order.customer_id), class: "link" do %>
          <h5><%= @order.customer.last_name %><%= @order.customer.first_name %></h5>
        <% end %>
      </td>
    </tr>
    <tr>
      <th class="text-nowrap"><h5><strong>注文日</strong></h5></th>
      <td class="text-nowrap"><h5><%= @order.created_at.strftime('%Y/%m/%d') %></h5></td>
    </tr>
    <tr>
      <th class="text-nowrap d-flex align-items-start"><h5><strong>配送先</strong></h5></th>
      <td>
        <h5>
          〒<%= @order.postal_code %>　<%= @order.address %><br/>
          <%= @order.name %>
        </h5>
      </td>
    </tr>
    <tr>
      <th class="text-nowrap"><h5><strong>支払方法</strong></h5></th>
      <td class="text-nowrap"><h5><%= @order.payment_method_i18n %></h5></td>
    </tr>
    <tr>
      <th><h5 class="mr-5 text-nowrap"><strong>注文ステータス</strong></h5></th>
      <td>
        <%= form_with model: @order, url: admin_order_path, method: :patch, class: "d-flex" do |f| %>
          <%= f.select :status, Order.statuses_i18n.invert, {prompt: false}, class: "form-control form-control-sm col-4 mr-5 text-center" %>
          <%= f.submit "更新", class: "btn btn-success py-0" %>
        <% end %>
      </td>
    </tr>
  </table>

  <div class="row my-4">
    <table class="table table-borderless border-top border-bottom col-8">
      <thead class="thead-light">
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order_details.each do |order_detail| %>
          <tr>
            <td class="text-nowrap"><%= order_detail.item.name %></td>
            <td class="text-nowrap"><%= order_detail.price.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td class="text-nowrap"><%= order_detail.subtotal.to_s(:delimited) %></td>
            <td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: true, class: "d-flex" do |f| %>
                <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert, {prompt: false}, class: "form-control form-control-sm col-6 mr-4 text-center" %>
                <%= f.submit "更新", class: "btn btn-success py-0" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <table class="col-3 ml-auto d-flex align-items-end">
      <tr>
        <th class="text-nowrap"><h5><strong>商品合計</strong></h5></th>
        <td class="text-nowrap text-right"><h5><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %>円</h5></td>
      </tr>
      <tr>
        <th class="text-nowrap"><h5><strong>送料</strong></h5></th>
        <td class="text-nowrap text-right"><h5><%= @order.shipping_cost.to_s(:delimited) %>円</h5></td>
      </tr>
      <tr>
        <th><h5 class="text-nowrap mr-3"><strong>請求金額合計</strong></h5></th>
        <td class="text-nowrap text-right"><h5>
          <strong><%= @order.total_payment.to_s(:delimited) %>円</strong>
        </h5></td>
      </tr>
    </table>
  </div>
</div>