config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: 'public' do
    root to: "homes#top"
    get 'homes/about'
    get "customers/current_customer" => "customers#show"
    get "customers/confirm"
    patch "customers/withdraw" => "customers#withdraw"
    delete "cart_items/destroy_all"
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks"
    resources :items, only: [:index, :show]
    resources :customers, only: [:edit, :update, :withdraw]
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :create, :index, :show]
  end

  namespace :admin do
    root to: "homes#top"
    get "orders/customer_show/:id" => "orders#customer_show"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true, length: {minimum: 2}
  validates :postal_code, presence: true, length: {is: 7}, numericality: true
  validates :address, presence: true

  def address_display
    '〒' + postal_code + '　' + address + '　' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def active_for_authentication?
    super && (is_deleted == false)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders

  def customer_address_display
    '〒' + postal_code + '　' + address + '　' + last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true, length: {in: 1..10}
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  validates :name, presence: true
  validates :introduction, presence: true, length: {in: 2..50}
  validates :price, presence: true, numericality: {only_integer: true}

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def with_tax_price
     (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  has_many :order_details
  belongs_to :customer

  validates :postal_code, presence: true, length: {is: 7}, numericality: true
  validates :address, presence: true
  validates :name, presence: true, length: {minimum: 2}
  validates :payment_method, presence: true

  enum status: {
    wait_payment: 0,
    confirm_payment: 1,
    making: 2,
    preparing_ship: 3,
    finish_prepare: 4
  }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status:{
    impossible_making: 0,
    waiting_making: 1,
    making: 2,
    finish: 3
  }

  def subtotal
    price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    if genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      redirect_to admin_item_path(params[:id])
    else
      render :edit
    end
  end

  private
    def item_params
      params.require(:item).permit(:name, :image, :introduction, :price, :genre_id, :is_active)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
  def customer_status_name(customer)
    if customer.is_deleted
      '退会'
    else
      '有効'
    end
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
  def admin_item_status_name(item)
    if item.is_active
      '販売中'
    else
      '販売停止中'
    end
  end
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/71f8f10969.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand p-3 col-12 col-md-4 col-lg-3" href="/">
            <h2 class="col-12 text-center m-0">
              ながのCAKE <i class="fas fa-coffee"></i>
            </h2>
          </a>

          <% if customer_signed_in? %>
            <p class="text-nowrap col-6 col-md-4 col-lg-3 d-flex align-items-center m-0 px-5 pl-md-0">
              ようこそ、<%= current_customer.last_name %>さん！
            </p>
          <% end %>

          <div class="gnav">
            <div class="row">
              <button class="navbar-toggler mr-2" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-lg-auto py-2">
                  <% if customer_signed_in? %>
                    <li class="nav-item mr-lg-4 mr-md-2 mr-0">
                      <%= link_to "マイページ", customers_current_customer_path, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                    <li class="nav-item mr-lg-4 mr-md-2 mr-0">
                      <%= link_to "商品一覧", items_path, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                    <li class="nav-item mr-lg-4 mr-md-2 mr-0">
                      <%= link_to "カート", cart_items_path, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                  <% elsif admin_signed_in? %>
                    <li class="nav-item mr-lg-4 mr-md-2 mr-0">
                      <%= link_to "商品一覧", admin_items_path, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                    <li class="nav-item mr-lg-4 mr-md-2 mr-0">
                      <%= link_to "会員一覧", admin_customers_path, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                    <li class="nav-item mr-lg-4 mr-md-2 mr-0">
                      <%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                    <li class="nav-item mr-lg-4 mr-md-2 mr-0">
                      <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                  <% else %>
                    <li class="nav-item mr-lg-4 mr-md-2 mr-0">
                      <%= link_to "About", homes_about_path, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                    <li class="nav-item mr-lg-4 mr-md-2 mr-0">
                      <%= link_to "商品一覧", items_path, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                    <li class="nav-item mr-lg-4 mr-md-2 mr-0">
                      <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "ログイン", customer_session_path, class: 'nav-link bg-light text-nowrap rounded border border-secondary' %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
      <p class="m-3"><%= flash[:notice] %></p>
      <%= yield %>
    </main>

    <footer class="bg-light p-5"></footer>
  </body>
</html>